### PR TITLE
3.0: Fix slurm version: 20.11.7

### PR DESCRIPTION
**Pull request by gmarciani**
### Changes
1. Fixed slurm version: 20.11.7

### Testing
1. Tested on Jenkins (kitchen test)

### CODE REVIEW

**Comment by enrico-usai** [comment]
The patch is incomplete, you can cherry pick this commit: https://github.com/aws/aws-parallelcluster-cookbook/pull/950

Remember you need to fix che cli too: https://github.com/aws/aws-parallelcluster/pull/2742

**Review by enrico-usai — CHANGES_REQUESTED** [review]
The patch is incomplete, you can cherry pick this commit: #950
Remember you need to fix che cli too: aws/aws-parallelcluster#2742

**Comment by gmarciani** [comment]
The commit your're asking me to cherry-pick is [this](https://github.com/aws/aws-parallelcluster-cookbook/commit/ec6de83b458a1fd05905608bb894754652e221c5), which makes changes to `attributes/default.rb` that looks incompatible, i.e. `default['cfncluster']['slurm']` properties rather than `default['cluster']['slurm']` properties.

Should I cherry-pick it for changes in `CHANGELOG.md` and `recipes/slurm_install.rb`?

**Comment by enrico-usai** [comment]
Closed in favour of: https://github.com/aws/aws-parallelcluster-cookbook/pull/958

**Pull request closed without merging**
